/**
 * Distribution-records Excel export (client-side).
 *
 * Faithfully reproduces STEPD's operator report — the per-program YouTube upload
 * metadata sheet generated by `src/server/routes/reports.ts` (GET
 * /admin/reports/clips-excel), which itself mirrors the hand-kept sheet
 * docs/dev/메타데이터 [ENA].xlsx. Same library (exceljs), same 8 columns, widths,
 * bold header and yyyy-mm-dd number format — so the output drops into the
 * finance team's existing workflow unchanged.
 *
 * v2 is a mock/client prototype, so the workbook is built in the browser and
 * downloaded via a Blob. Backend mapping: this becomes the server route
 * above — see the mapping notes at the bottom of this file and
 * docs/plans/publish-fields-ux-plan.md §7.
 */

import type ExcelJSNS from "exceljs";
import {
  CLIP_TYPES,
  DISTRIBUTION_CHANNELS,
  type DistributionChannel,
} from "@/lib/constants";
import type { Clip, DistributionState, Episode, Program } from "@/lib/types";

export interface ExportData {
  programs: Program[];
  episodes: Episode[];
  clips: Clip[];
}

/** Rough per-channel view estimate (matches the analytics screen). Real figures wire in at M6. */
const EST_VIEWS: Record<DistributionChannel, number> = { smr: 82000, youtube: 124000, meta: 45000 };

const DIST_STATUS_LABEL: Record<string, string> = {
  published: "게시됨",
  scheduled: "예약됨",
  pending: "업로드 중",
  failed: "실패",
  none: "—",
};

/** Parse a v2 reserve string "YYYYMMDDHHmmss" → Date (mirrors reports.ts parseReserveDate). */
export function parseReserveDate(reserveDate: string | null | undefined): Date | null {
  if (!reserveDate || reserveDate.length !== 14) return null;
  const y = Number(reserveDate.slice(0, 4));
  const mo = Number(reserveDate.slice(4, 6)) - 1;
  const d = Number(reserveDate.slice(6, 8));
  const h = Number(reserveDate.slice(8, 10));
  const mi = Number(reserveDate.slice(10, 12));
  const s = Number(reserveDate.slice(12, 14));
  return new Date(y, mo, d, h, mi, s);
}

function clipTypeLabel(clipType: string): string {
  return (CLIP_TYPES as Record<string, string>)[clipType] ?? clipType;
}

function youtubeUrl(videoId: string): string {
  return `https://youtu.be/${videoId}`;
}

/**
 * STEPD-faithful YouTube metadata sheet, one per program (reports.ts:65-98).
 * Only clips that are YouTube-published with an external video id are included.
 */
function addYoutubeMetadataSheets(
  workbook: ExcelJSNS.Workbook,
  data: ExportData,
): number {
  const episodeById = new Map(data.episodes.map((e) => [e.id, e]));
  let rowCount = 0;

  for (const program of data.programs) {
    const programClips = data.clips.filter((c) => {
      const ep = episodeById.get(c.episodeId);
      return ep?.programId === program.id;
    });
    const rows: { clip: Clip; yt: DistributionState }[] = [];
    for (const clip of programClips) {
      const yt = clip.distributions.find(
        (d) => d.channel === "youtube" && d.status === "published" && d.externalId,
      );
      if (yt) rows.push({ clip, yt });
    }

    if (rows.length === 0) continue;

    const sheet = workbook.addWorksheet(program.title.slice(0, 31) || "clips");
    sheet.columns = [
      { header: "공개일자", key: "publishedAt", width: 14 },
      { header: "회차", key: "episode", width: 8 },
      { header: "콘텐츠유형", key: "clipType", width: 12 },
      { header: "클립명", key: "title", width: 60 },
      { header: "Youtube url", key: "url", width: 32 },
      { header: "ID", key: "videoId", width: 14 },
      { header: "내용", key: "synopsis", width: 50 },
      { header: "STEP D 가동여부", key: "stepdOperated", width: 14 },
    ];
    sheet.getRow(1).font = { bold: true };

    for (const { clip, yt } of rows) {
      const episode = episodeById.get(clip.episodeId);
      const publishedAt = parseReserveDate(yt.reserveDate);
      const videoId = yt.externalId as string;
      const row = sheet.addRow({
        publishedAt: publishedAt ?? "",
        episode: episode?.episodeNumber ?? "",
        clipType: clipTypeLabel(clip.clipType),
        title: clip.title,
        url: youtubeUrl(videoId),
        videoId,
        synopsis: clip.synopsis ?? "",
        stepdOperated: "O",
      });
      if (publishedAt) row.getCell("publishedAt").numFmt = "yyyy-mm-dd";
      rowCount += 1;
    }
  }
  return rowCount;
}

/**
 * v2 extension — all-channel distribution records (clip × channel × status ×
 * 공개일시 × 성과). Same column DNA/formatting as the STEPD sheet, widened to the
 * full channel matrix the operator works across.
 */
function addDistributionRecordsSheet(
  workbook: ExcelJSNS.Workbook,
  data: ExportData,
): number {
  const episodeById = new Map(data.episodes.map((e) => [e.id, e]));
  const sheet = workbook.addWorksheet("배포 기록");
  sheet.columns = [
    { header: "공개일시", key: "publishedAt", width: 18 },
    { header: "프로그램", key: "program", width: 20 },
    { header: "회차", key: "episode", width: 8 },
    { header: "콘텐츠유형", key: "clipType", width: 12 },
    { header: "클립명", key: "title", width: 44 },
    { header: "채널", key: "channel", width: 12 },
    { header: "상태", key: "status", width: 10 },
    { header: "URL", key: "url", width: 30 },
    { header: "예상조회수", key: "estViews", width: 12 },
    { header: "내용", key: "synopsis", width: 44 },
  ];
  sheet.getRow(1).font = { bold: true };

  let rowCount = 0;
  for (const clip of data.clips) {
    const episode = episodeById.get(clip.episodeId);
    for (const dist of clip.distributions) {
      if (dist.status === "none") continue;
      const publishedAt = parseReserveDate(dist.reserveDate);
      const row = sheet.addRow({
        publishedAt: publishedAt ?? "",
        program: clip.programTitle,
        episode: episode?.episodeNumber ?? "",
        clipType: clipTypeLabel(clip.clipType),
        title: clip.title,
        channel: DISTRIBUTION_CHANNELS[dist.channel],
        status: DIST_STATUS_LABEL[dist.status] ?? dist.status,
        url: dist.channel === "youtube" && dist.externalId ? youtubeUrl(dist.externalId) : "",
        estViews: dist.status === "published" ? EST_VIEWS[dist.channel] : "",
        synopsis: clip.synopsis ?? "",
      });
      if (publishedAt) row.getCell("publishedAt").numFmt = "yyyy-mm-dd hh:mm";
      row.getCell("estViews").numFmt = "#,##0";
      rowCount += 1;
    }
  }
  return rowCount;
}

export interface ExportResult {
  filename: string;
  youtubeRows: number;
  recordRows: number;
}

/**
 * Build the workbook (per-program STEPD sheets + all-channel records) and trigger
 * a browser download. Returns counts for a confirmation toast.
 */
export async function exportDistributionExcel(
  data: ExportData,
  stamp: string,
): Promise<ExportResult> {
  const ExcelJS = (await import("exceljs")).default;
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "STEP D";

  const recordRows = addDistributionRecordsSheet(workbook, data);
  const youtubeRows = addYoutubeMetadataSheets(workbook, data);

  const filename = `배포기록_${stamp}.xlsx`;
  const buffer = await workbook.xlsx.writeBuffer();
  downloadBlob(
    new Blob([buffer], {
      type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    }),
    filename,
  );
  return { filename, youtubeRows, recordRows };
}

function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.rel = "noopener";
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

/*
 * ── Backend mapping (M6) ────────────────────────────────────────────────────
 * v2 client build → STEPD server route `GET /admin/reports/clips-excel`:
 *   - addYoutubeMetadataSheets ↔ reports.ts (exact 8-column sheet). v2 fields →
 *     STEPD: clip.synopsis → clip.synopsis; dist.externalId → dist.metadata
 *     .youtubeVideoId; dist.reserveDate → dist.reserveDate; episode.episodeNumber
 *     → content.contentNumber; the isUse!=='N' + videoId filter ↔ our
 *     status==='published' + externalId filter.
 *   - At M6 the export button hits the server route (streamed xlsx) instead of
 *     building client-side; addDistributionRecordsSheet becomes a new report
 *     endpoint (all channels) or stays client-side over the loaded dataset.
 */
