/**
 * Distribution-records Excel export (client-side).
 *
 * Faithfully reproduces STEPD's operator report — the per-program YouTube upload
 * metadata sheet generated by `src/server/routes/reports.ts` (GET
 * /admin/reports/clips-excel), which itself mirrors the hand-kept sheet
 * docs/dev/메타데이터 [ENA].xlsx. Same library (exceljs), same 8 columns, widths,
 * bold header and yyyy-mm-dd number format — so the output drops into the
 * finance team's existing workflow unchanged.
 *
 * v2 is a mock/client prototype, so the workbook is built in the browser and
 * downloaded via a Blob. Backend mapping: this becomes the server route
 * above — see the mapping notes at the bottom of this file and
 * docs/plans/publish-fields-ux-plan.md §7.
 */

import type ExcelJSNS from "exceljs";
import { channelLabel, CLIP_TYPES } from "@/lib/constants";
import type { Clip, DistributionState, Episode, Program } from "@/lib/types";

export interface ExportData {
  programs: Program[];
  episodes: Episode[];
  clips: Clip[];
}

/**
 * 상태 라벨.
 *
 * `recorded` 를 빠뜨리면 Meta·TikTok·SMR 건이 영문 'recorded' 로 찍혀서, **실제 게시**와
 * **상태 기록만 한 것**의 구분이 내보낸 파일에서 사라진다. 라벨에 그 차이를 적어 둔다.
 */
const DIST_STATUS_LABEL: Record<string, string> = {
  published: "게시됨",
  recorded: "기록됨(실업로드 아님)",
  scheduled: "예약됨",
  pending: "업로드 중",
  failed: "실패",
  none: "—",
};

/**
 * 예약 시각 문자열 → Date.
 *
 * 형식이 두 가지다. 실제로 저장되는 값은 배포 모달의 `<input type="datetime-local">` 그대로인
 * `"2026-08-11T10:00"`(초가 붙으면 19자)이고, 서버·워커는 이 문자열을 가공 없이 넘긴다.
 * `"YYYYMMDDHHmmss"` 14자리는 구 STEPD(reports.ts) 유산이라 옛 데이터에만 남아 있다.
 * **14자리만 받던 시절엔 이 열이 프로덕션에서 늘 빈칸이었다** — 둘 다 받는다.
 */
export function parseReserveDate(reserveDate: string | null | undefined): Date | null {
  if (!reserveDate) return null;

  if (/^\d{14}$/.test(reserveDate)) {
    const y = Number(reserveDate.slice(0, 4));
    const mo = Number(reserveDate.slice(4, 6)) - 1;
    const d = Number(reserveDate.slice(6, 8));
    const h = Number(reserveDate.slice(8, 10));
    const mi = Number(reserveDate.slice(10, 12));
    const s = Number(reserveDate.slice(12, 14));
    return new Date(y, mo, d, h, mi, s);
  }

  // datetime-local 은 타임존이 없는 로컬 시각이다. new Date("...T10:00") 는 브라우저마다
  // UTC 로 읽는 경우가 있어 직접 분해한다.
  const m = /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})(?::(\d{2}))?$/.exec(reserveDate);
  if (!m) return null;
  const dt = new Date(
    Number(m[1]),
    Number(m[2]) - 1,
    Number(m[3]),
    Number(m[4]),
    Number(m[5]),
    Number(m[6] ?? 0),
  );
  return Number.isNaN(dt.getTime()) ? null : dt;
}

function clipTypeLabel(clipType: string): string {
  return (CLIP_TYPES as Record<string, string>)[clipType] ?? clipType;
}

function youtubeUrl(videoId: string): string {
  return `https://youtu.be/${videoId}`;
}

/**
 * STEPD-faithful YouTube metadata sheet, one per program (reports.ts:65-98).
 * Only clips that are YouTube-published with an external video id are included.
 */
function addYoutubeMetadataSheets(
  workbook: ExcelJSNS.Workbook,
  data: ExportData,
): number {
  const episodeById = new Map(data.episodes.map((e) => [e.id, e]));
  let rowCount = 0;

  for (const program of data.programs) {
    const programClips = data.clips.filter((c) => {
      const ep = episodeById.get(c.episodeId);
      return ep?.programId === program.id;
    });
    const rows: { clip: Clip; yt: DistributionState }[] = [];
    for (const clip of programClips) {
      const yt = clip.distributions.find(
        (d) => d.channel === "youtube" && d.status === "published" && d.externalId,
      );
      if (yt) rows.push({ clip, yt });
    }

    if (rows.length === 0) continue;

    const sheet = workbook.addWorksheet(program.title.slice(0, 31) || "clips");
    sheet.columns = [
      { header: "공개일자", key: "publishedAt", width: 14 },
      { header: "회차", key: "episode", width: 8 },
      { header: "콘텐츠유형", key: "clipType", width: 12 },
      { header: "클립명", key: "title", width: 60 },
      { header: "Youtube url", key: "url", width: 32 },
      { header: "ID", key: "videoId", width: 14 },
      { header: "내용", key: "synopsis", width: 50 },
      { header: "STEP D 가동여부", key: "stepdOperated", width: 14 },
    ];
    sheet.getRow(1).font = { bold: true };

    for (const { clip, yt } of rows) {
      const episode = episodeById.get(clip.episodeId);
      const publishedAt = parseReserveDate(yt.reserveDate);
      const videoId = yt.externalId as string;
      const row = sheet.addRow({
        publishedAt: publishedAt ?? "",
        episode: episode?.episodeNumber ?? "",
        clipType: clipTypeLabel(clip.clipType),
        title: clip.title,
        url: youtubeUrl(videoId),
        videoId,
        synopsis: clip.synopsis ?? "",
        stepdOperated: "O",
      });
      if (publishedAt) row.getCell("publishedAt").numFmt = "yyyy-mm-dd";
      rowCount += 1;
    }
  }
  return rowCount;
}

/**
 * v2 extension — all-channel distribution records (clip × channel × status ×
 * 공개일시). Same column DNA/formatting as the STEPD sheet, widened to the
 * full channel matrix the operator works across. 성과(조회수) 컬럼은 없다 —
 * 실 지표 배선 전까지는 비워 두는 것보다 컬럼 자체가 없는 편이 오해가 적다.
 */
function addDistributionRecordsSheet(
  workbook: ExcelJSNS.Workbook,
  data: ExportData,
): number {
  const episodeById = new Map(data.episodes.map((e) => [e.id, e]));
  const sheet = workbook.addWorksheet("배포 기록");
  sheet.columns = [
    { header: "공개일시", key: "publishedAt", width: 18 },
    { header: "프로그램", key: "program", width: 20 },
    { header: "회차", key: "episode", width: 8 },
    { header: "콘텐츠유형", key: "clipType", width: 12 },
    { header: "클립명", key: "title", width: 44 },
    { header: "채널", key: "channel", width: 12 },
    { header: "상태", key: "status", width: 10 },
    { header: "URL", key: "url", width: 30 },
    // 조회수 컬럼은 뺐다 — 채널별 하드코딩 상수를 "예상조회수" 로 내보내면 모든 YouTube 행이
    // 같은 값으로 찍혀서 파일만 보는 사람에게는 실측치처럼 유통된다. 실제 지표를
    // /api/youtube/analytics 에서 채우게 되면 그때 되살린다.
    { header: "내용", key: "synopsis", width: 44 },
  ];
  sheet.getRow(1).font = { bold: true };

  let rowCount = 0;
  for (const clip of data.clips) {
    const episode = episodeById.get(clip.episodeId);
    for (const dist of clip.distributions) {
      if (dist.status === "none") continue;
      const publishedAt = parseReserveDate(dist.reserveDate);
      const row = sheet.addRow({
        publishedAt: publishedAt ?? "",
        program: clip.programTitle,
        episode: episode?.episodeNumber ?? "",
        clipType: clipTypeLabel(clip.clipType),
        title: clip.title,
        channel: channelLabel(dist.channel),
        status: DIST_STATUS_LABEL[dist.status] ?? dist.status,
        url: dist.channel === "youtube" && dist.externalId ? youtubeUrl(dist.externalId) : "",
        synopsis: clip.synopsis ?? "",
      });
      if (publishedAt) row.getCell("publishedAt").numFmt = "yyyy-mm-dd hh:mm";
      rowCount += 1;
    }
  }
  return rowCount;
}

export interface ExportResult {
  filename: string;
  youtubeRows: number;
  recordRows: number;
}

/**
 * Build the workbook (per-program STEPD sheets + all-channel records) and trigger
 * a browser download. Returns counts for a confirmation toast.
 */
export async function exportDistributionExcel(
  data: ExportData,
  stamp: string,
): Promise<ExportResult> {
  const ExcelJS = (await import("exceljs")).default;
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "STEP D";

  const recordRows = addDistributionRecordsSheet(workbook, data);
  const youtubeRows = addYoutubeMetadataSheets(workbook, data);

  const filename = `배포기록_${stamp}.xlsx`;
  const buffer = await workbook.xlsx.writeBuffer();
  downloadBlob(
    new Blob([buffer], {
      type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    }),
    filename,
  );
  return { filename, youtubeRows, recordRows };
}

function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.rel = "noopener";
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

/*
 * ── Backend mapping (M6) ────────────────────────────────────────────────────
 * v2 client build → STEPD server route `GET /admin/reports/clips-excel`:
 *   - addYoutubeMetadataSheets ↔ reports.ts (exact 8-column sheet). v2 fields →
 *     STEPD: clip.synopsis → clip.synopsis; dist.externalId → dist.metadata
 *     .youtubeVideoId; dist.reserveDate → dist.reserveDate; episode.episodeNumber
 *     → content.contentNumber; the isUse!=='N' + videoId filter ↔ our
 *     status==='published' + externalId filter.
 *   - At M6 the export button hits the server route (streamed xlsx) instead of
 *     building client-side; addDistributionRecordsSheet becomes a new report
 *     endpoint (all channels) or stays client-side over the loaded dataset.
 */
